// Term screening for submitted text.
//
// The brief's list is a list of term FAMILIES, not of surface forms. Nobody
// types "nigger" into a form that blocks it; they type "n1gg3r", "n i g g e r",
// or "niiigggerrr". So the variants are generated by folding the input, never
// curated one by one:
//
//   1. Unicode confusables and diacritics collapse to plain ASCII.
//   2. Leetspeak folds back to letters.
//   3. Separators disappear, and runs of single letters rejoin into a word.
//   4. Repeated letters collapse, on BOTH sides of the comparison, so the
//      needle and the haystack end up in the same canonical space.
//
// The opposite failure matters just as much. Substring scanning is what gives
// you the Scunthorpe problem, so almost nothing here is matched as a raw
// substring of the whole text:
//
//   exact   the pattern must BE a token (plus a short suffix). Used for every
//           short or ambiguous term - ass, fag, jap, sex, cock, coon. "class"
//           and "Essex" are different tokens, so they are simply never seen.
//   family  the pattern must be a substring of ONE token. Catches "fucking"
//           and "niggerz" without ever gluing "wish" and "it" into "shit".
//   phrase  two words with anything between them - "sand nigger", "blow job".
//
// And an allowlist of real words runs first: a token that is Nigeria, or
// Scunthorpe, or analysis, is dropped before any matching happens, so it
// cannot be part of a hit at all.

// --- normalisation ---------------------------------------------------------

// Confusables that survive NFKD: Cyrillic and Greek lookalikes, and the
// leetspeak that any filter is expected to see. `1` folds to `i` rather than
// `l` because the terms in the list want an i far more often.
const FOLD = new Map(Object.entries({
  "0": "o", "1": "i", "2": "z", "3": "e", "4": "a", "5": "s",
  "6": "g", "7": "t", "8": "b", "9": "g",
  "@": "a", "$": "s", "!": "i", "|": "i", "€": "e", "£": "e",
  // Cyrillic
  "а": "a", "в": "b", "с": "c", "е": "e", "н": "h", "к": "k", "м": "m",
  "о": "o", "р": "p", "т": "t", "у": "y", "х": "x", "і": "i", "ѕ": "s",
  "г": "r", "д": "d", "з": "z", "ц": "u", "ч": "h", "л": "l", "б": "b",
  "ф": "f", "ј": "j", "ԁ": "d", "ɡ": "g", "ѡ": "w", "ⅰ": "i", "ᴏ": "o",
  // Greek
  "α": "a", "β": "b", "ε": "e", "ι": "i", "κ": "k", "ν": "v", "ο": "o",
  "ρ": "p", "τ": "t", "υ": "u", "χ": "x", "ѵ": "v",
}));

/**
 * Text -> lowercase ASCII letters, digits folded to letters, everything else
 * left in place as a separator. Deliberately NOT stripping separators yet:
 * tokenisation needs to see where the gaps are.
 */
export function normalize(text) {
  const folded = text
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "") // combining marks: café -> cafe
    .toLowerCase();

  let out = "";
  for (const ch of folded) out += FOLD.get(ch) ?? ch;

  // ph -> f is the one multi-character fold worth having: phuck, phag, phaggot.
  // It cannot create a hit out of an innocent word, because every term it can
  // produce (fuck, fag) is on the list under its own spelling anyway.
  return out.replace(/ph/g, "f");
}

/** Runs of the same letter collapse to one. Applied to needle AND haystack. */
export function collapse(word) {
  return word.replace(/(.)\1+/g, "$1");
}

/**
 * Normalised text -> the tokens we actually match against.
 *
 * Two things happen here that a plain split does not do.
 *
 * Runs of very short tokens are glued back together, because that is what
 * letter-spacing obfuscation looks like: "f u c k" and "s.h.i.t" arrive as
 * four one-character tokens, while ordinary prose does not. Only runs of two
 * or more short tokens merge, so "wish it" stays two words - which is exactly
 * the pair that a naive "strip all spaces" would turn into "shit".
 *
 * And allowlisted words are dropped, not kept: Scunthorpe is removed from the
 * stream entirely, so it cannot contribute letters to any match. Dropping is
 * safe because the neighbours still join up - "ni gger" is still caught.
 */
export function tokenize(normalized) {
  const raw = normalized.split(/[^a-z0-9]+/).filter(Boolean);

  const merged = [];
  let run = [];
  const flushRun = () => {
    if (run.length > 1) merged.push(run.join(""));
    else if (run.length === 1) merged.push(run[0]);
    run = [];
  };
  for (const token of raw) {
    if (token.length <= 2) run.push(token);
    else {
      flushRun();
      merged.push(token);
    }
  }
  flushRun();

  return merged.filter((token) => !isAllowed(token));
}

// --- the false-positive allowlist ------------------------------------------
//
// Ordinary words that contain a listed term. Every one of these was a real
// overblock somewhere, and the list is meant to grow rather than to be clever.

const ALLOW = new Set([
  // -nigger / -nigga
  "niger", "nigeria", "nigerian", "nigerien", "niggle", "niggling", "niggard",
  "niggardly", "snigger", "sniggering", "snigg",
  // -coon
  "raccoon", "cocoon", "tycoon", "lagoon", "saloon", "spoon", "harpoon",
  "monsoon", "balloon", "cartoon", "platoon", "baboon", "buffoon", "maroon",
  "typhoon", "cocoa", "coconut", "coop", "scooter",
  // -cock
  "cocktail", "cockpit", "cockroach", "cockatoo", "cockney", "peacock",
  "hancock", "woodcock", "shuttlecock", "cocker", "cockburn", "cockfosters",
  "cockermouth", "cockle", "stopcock", "weathercock",
  // -cunt
  "scunthorpe",
  // -dick
  "dickens", "dickinson", "dickson", "benedict", "dictionary", "predict",
  "verdict", "indicate", "dedicate", "medic", "medical", "addict", "edict",
  // -ass / -arse
  "assassin", "assassinate", "assess", "assessment", "asset", "assign",
  "assist", "assistant", "associate", "association", "assume", "assure",
  "assemble", "assembly", "assert", "assign", "class", "classic", "classroom",
  "glass", "grass", "brass", "pass", "password", "passage", "passenger",
  "mass", "massive", "massage", "bass", "bypass", "compass", "embassy",
  "harass", "potassium", "cassette", "lass", "amass", "morass", "carcass",
  "surpass", "cassava", "assay", "sparse", "hearse", "coarse", "parse",
  // -anal
  "analysis", "analyse", "analyze", "analytics", "analytical", "analyst",
  "canal", "banal", "analog", "analogue", "analogy", "anale",
  // -sex
  "essex", "sussex", "middlesex", "wessex", "sexton", "sextant", "sextet",
  // -rape / -rapist
  "therapist", "therapy", "grape", "drape", "scrape", "trapeze", "therapeutic",
  // -cum
  "document", "cumulative", "cumulus", "circumstance", "circumvent",
  "accumulate", "cucumber", "incumbent", "succumb", "scum", "vacuum",
  "cumin", "curriculum", "spectrum", "album", "acumen",
  // -tit
  "titan", "titanic", "title", "competitive", "constitute", "entity",
  "identity", "subtitle", "petition", "appetite", "attitude", "institute",
  "quantity", "partition", "repetition", "gratitude", "altitude", "latitude",
  // -shit
  "shiitake", "shitake",
  // -hell
  "shell", "shelter", "michelle", "hellenic", "othello", "hello",
  // -gook
  "gobbledygook",
  // -pedo
  "torpedo", "pedometer", "pedestrian", "pedal", "pedigree", "pedantic",
  // -retard
  "retardant", "retardation",
  // -spic
  "auspicious", "auspices", "suspicion", "suspicious", "conspicuous",
  "despicable", "spice", "spicy", "spices",
  // -jap
  "japan", "japanese", "jape",
  // -crap
  "scrap", "scrapbook", "scrapyard",
  // -fag
  "fagus",
  // -boner
  "carbonera",
]);

const PLURAL = /(?:s|es|ed|ing|er|ers|ies|y)$/;

function isAllowed(token) {
  if (ALLOW.has(token)) return true;
  const stem = token.replace(PLURAL, "");
  return stem.length >= 4 && ALLOW.has(stem);
}

// --- the term list ---------------------------------------------------------
//
// It lives in terms.js, and the split is deliberate rather than cosmetic.
// Everything above is technique - the folding, the tokenising, the allowlist
// that keeps Scunthorpe out of trouble - and technique is worth sharing. The
// list is the opposite: printed anywhere, it becomes a set of instructions for
// getting past this filter. So the engine is publishable and the list is not,
// and tools/sync_public.mjs knows the difference.
//
// Severity drives what happens, and the mapping is in moderation.js:
//   high    -> rejected, silently
//   medium  -> pending, a human looks
//   low     -> printed, but recorded so the admin page can show it

import { TERMS } from "./terms.js";

export { TERMS };

// Identity words are NOT on any list, on purpose. "gay", "queer", "lesbian",
// "trans", "black", "jew", "muslim" and their neighbours are how people
// describe themselves. Blocking them would be the loudest failure this filter
// could have, and it would be invisible to us: the author just sees the same
// polite confirmation as everyone else.

// The suffixes an `exact` term may carry and still be the same word.
const SUFFIXES = ["", "s", "z", "es", "ed", "ing", "er", "ers", "ies", "y"];

const SEVERITY_RANK = { low: 1, medium: 2, high: 3 };

function matchesExact(token, pattern) {
  if (!token.startsWith(pattern)) return false;
  return SUFFIXES.includes(token.slice(pattern.length));
}

/**
 * Screens one message.
 * @returns {{severity: string|null, terms: string[]}} the worst severity hit,
 *          and every family that matched, for the admin page to show.
 */
/**
 * Every way of gluing 2 to 4 adjacent tokens back together.
 *
 * The short-run merge in tokenize() only fires on runs of tokens of one or two
 * characters, which is what "f u c k" looks like. It does nothing for "ni
 * gger" or "n igg er", where the pieces are uneven - and those got through.
 *
 * Raising the merge threshold to three characters would catch them and would
 * also glue "he was hit by a car" into something containing "shit", so that
 * door stays shut. Instead these candidates are matched WHOLE, never as
 * substrings: "ni"+"gger" is exactly "nigger" and is caught, while "wish"+"it"
 * is "wishit", which is not any term, and is not.
 *
 * That whole-string rule is the entire safety of this function. Loosening it
 * to a substring match would reintroduce the Scunthorpe problem through the
 * back door.
 */
function glued(tokens) {
  const out = [];
  for (let i = 0; i < tokens.length; i++) {
    let joined = tokens[i];
    for (let span = 1; span < 4 && i + span < tokens.length; span++) {
      joined += tokens[i + span];
      if (joined.length <= 24) out.push(joined);
    }
  }
  return out;
}

export function screen(text) {
  const normalized = normalize(String(text ?? ""));
  const tokens = tokenize(normalized);
  const pieces = glued(tokens);
  // The words as they were actually written, with nothing merged and nothing
  // dropped. `tokens` glues runs of short tokens together to defeat letter
  // spacing, which is right for matching and wrong for reading context: in
  // "a du retard" it produces "adu", and the determiner that makes the phrase
  // French disappears. Context is read here instead.
  const plain = normalized.split(/[^a-z0-9]+/).filter(Boolean);
  // Collapsed forms are only used by family and phrase matching. Applying them
  // to `exact` would turn the ordinary word "as" into "ass", and "Bob's" into
  // "boobs" - the collapse is a strong fold and it needs a long word to be safe.
  const collapsedTokens = tokens.map(collapse);
  const hits = new Set();
  let worst = null;

  const hit = (term) => {
    hits.add(term.id);
    if (!worst || SEVERITY_RANK[term.severity] > SEVERITY_RANK[worst]) {
      worst = term.severity;
    }
  };

  for (const term of TERMS) {
    for (const pattern of term.patterns) {
      let found = false;

      if (term.mode === "exact") {
        if (!term.exemptBefore && !term.exemptAfter) {
          found = tokens.some((t) => matchesExact(t, pattern));
        } else {
          // Where the word was written normally, its neighbours decide. Where
          // it only appears once short tokens have been glued back together,
          // it was spaced out on purpose, and no context excuses that.
          const written = plain
            .map((t, i) => i)
            .filter((i) => matchesExact(plain[i], pattern));
          found = written.length
            ? written.some((i) => !exempted(term, plain, i))
            : tokens.some((t) => matchesExact(t, pattern));
        }
      } else if (term.mode === "family") {
        const folded = collapse(pattern);
        found =
          tokens.some((t) => t.includes(pattern)) ||
          collapsedTokens.some((t) => t.includes(folded)) ||
          // Whole-string only, never a substring. See glued().
          pieces.some((p) => matchesExact(p, pattern) || matchesExact(collapse(p), folded));
      } else if (term.mode === "phrase") {
        // Two words, written apart, hyphenated, or run together. The gap is
        // capped so that "a rag on my head" is not a raghead.
        const [a, b] = pattern;
        const glued = a + b;
        found =
          tokens.some((t) => t.includes(glued)) ||
          collapsedTokens.some((t) => t.includes(collapse(glued))) ||
          new RegExp(`\\b${a}[^a-z0-9]{0,2}${b}`).test(normalized) ||
          adjacent(tokens, a, b);
      }

      if (found) {
        hit(term);
        break;
      }
    }
  }

  return { severity: worst, terms: [...hits] };
}

/**
 * Is this occurrence innocent because of the word next to it?
 *
 * Only used where one language's slur is another language's ordinary noun.
 * The exemption is per occurrence, not per message: "j'ai du retard, espece de
 * retard" still trips on the second one.
 */
function exempted(term, tokens, index) {
  const before = tokens[index - 1];
  const after = tokens[index + 1];
  if (term.exemptBefore && before && term.exemptBefore.includes(before)) return true;
  if (term.exemptAfter && after && term.exemptAfter.includes(after)) return true;
  return false;
}

/** True if token `a` is immediately followed by token `b`. */
function adjacent(tokens, a, b) {
  for (let i = 0; i < tokens.length - 1; i++) {
    if (matchesExact(tokens[i], a) && matchesExact(tokens[i + 1], b)) return true;
  }
  return false;
}
